### PR TITLE
Hotfix scrolling bug. Fixes #24

### LINKED ISSUE #24: Fix weird scrolling bug
Multiple scrollbars

### PR DESCRIPTION
**Pull request by meiamsome**

### CODE REVIEW

File: src/components/Template/index.js [hunk 1]
```diff
@@ -13,8 +13,8 @@ class Template extends React.Component {
     const { main } = this.props;
     return(
       <div>
-      <div style={{height: '100vh', position: 'relative'}}>
-          <Layout fixedHeader>
+      <div style={{minHeight: '100vh', position: 'relative'}}>
+          <Layout fixedHeader style={{position: 'relative', height: 'auto'}}>
```
Comment (cmanny) [inline src/components/Template/index.js]: It's good that you didn't use any CSS hacks here
